### ISSUE TITLE
Call to trait method implementation fails with signal 11

### ISSUE THREAD

**Issue by siy** [LedgerHQ/ledger-nanos-sdk#74]
I'm debugging an application which actively uses trait implementations and found that any call to a trait method implementation causes the application to fail with signal 11 in Speculos. Looks like vtable is not properly initialized after loading. Any ideas/suggestions?

**Comment by yhql** [comment]
Yes, this is an inherent limitation of the `ropi`/`rwpi` relocation model.
This can be solved by manually relocating the application when it boots, and should be solved with this PR https://github.com/LedgerHQ/ledger-nanos-sdk/pull/69 , which is not merged yet because it needs a few changes in my opinion. But hopefully at some point in the future, you won't have to do anything to get this to work.

**Comment by siy** [comment]
OK, I'll give it a try. Thanks for suggestion.
