### ISSUE TITLE
NVM crashes app on Nano S Plus

### ISSUE THREAD

**Issue by siy** [LedgerHQ/ledger-nanos-sdk#85]
Any attempt to use NVM on the Nano S Plus results in app panic, even if data accessed just for reading. 
The deeper investigation shows that panic happens in the method below (nvm.rs):
```
    fn which(&self) -> AtomicStorageElem {
        if self.storage_a.is_valid() {
            StorageA
        } else if self.storage_b.is_valid() {
            StorageB
        } else {
            panic!("invalidated atomic storage");
        }
    }
```
The same code works perfectly fine on Nano S.

Any ideas how to fix that?

**Comment by yhql** [comment]
Is this on device or in `speculos` ?
There is a limitation on speculos that prevents it from mapping the whole nvram_data section properly, so it remains uninitialized.

**Comment by siy** [comment]
Any updates?

**Comment by yhql** [comment]
Could you point to a repo that reproduces the issue?

**Comment by yhql** [comment]
The .data section does not contain the NVM storage, this number is related to something else. Usually apps are "forbidden" to include a `.data` section because it would not be initialized by the os when starting.

**Comment by yhql** [comment]
Thanks for the links.

You should use the `NVMData` wrapper in `nanos_sdk`, because it handles correct memory access for all devices. It works on Nano S because there's no need for the `rwpi` relocation model, but on Nano X and S+ this is [another story](https://github.com/LedgerHQ/ledger-nanos-sdk/blob/master/src/lib.rs#L158-L176)

The following works correctly on device:
```
#[link_section = ".nvm_data"]
static mut SETTINGS: NVMData<AtomicStorage<u32>> = NVMData::new(AtomicStorage::new(&3));
```

(We should update documentation in nvm.rs to reflect that some examples will not work unless going through NVMData @kingofpayne for information)

**Comment by siy** [comment]
Thanks. this change solved the issue.
