### ISSUE TITLE
screen/lock timeout

### ISSUE THREAD

**Issue by siy** [LedgerHQ/ledger-nanos-sdk#86]
Rust SDK handles events differently than `lib_standard_app` and this results in lack of processing of screen/lock timeouts.

**Comment by yhql** [comment]
While we're working into getting this handled by the OS directly instead of the current state of affairs, there are two options for a Rust app:
- Call `UxEvent::Event.request();` periodically (for example in your main event loop, on `ticker` events). This should trigger the screen lock automatically like C apps do
- Handle an explicit request for PIN in the same way: count ticker events manually and call `UxEvent::ValidatePIN.request()` when a limit is crossed

**Comment by siy** [comment]
One question: is there any kind of "reset" logic, which will restart timeout on other events, for example USB or user interaction? Due to the nature of the application, there are scenarios where interaction with the user may be quite long. I'd like to prevent device lock in the middle of the interaction.

**Comment by siy** [comment]
Opened a  #89 to enable proper handling of the screen timeouts.

**Comment by siy** [comment]
With #89 application seems is working as expected.
